services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $endpoint: '%digistrat.endpoint%'
            $token: '%digistrat.token%'

    Plugandcom\Bundle\DigistratBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'