services:
    Plugandcom\Bundle\DigistratBundle\Service\:
        autowire: true
        autoconfigure: true
        resource: '../../Service/*'
        arguments:
            $endpoint: '%digistrat.endpoint%'
            $token: '%digistrat.token%'